[package]
name = "bridge_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.136", features = ["derive"]}
serde_json = {version = "1.0.79"}
rand = "0.8.5"
itertools = "0.10.3"
arrayvec = {version = "0.7.2", features = ["serde"]}
ron = "0.7.0"
nom = "7.1.0"
karty = {path = "../karty", features = ["register", "parse"]}